[package]
name = "perlin_vox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.27.0"
ndarray = "0.15.6"
enterpolation = "0.2.1"
palette = "0.7.5"
fnv = "1.0.7"
twox-hash = "1.6.3"