[package]
name = "perlin_vox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
enterpolation = "0.2.1"
glam = "0.27.0"
ndarray = "0.15.6"
palette = "0.7.5"
rand = "0.8.5"